import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ibmArabic = localFont({
  src: [
    {
      path: "../public/fonts/IBM-Plex-Sans-Arabic/IBMPlexSansArabic-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/IBM-Plex-Sans-Arabic/IBMPlexSansArabic-Bold.otf",
      weight: "700",
      style: "bold",
    },
    {
      path: "../public/fonts/IBM-Plex-Sans-Arabic/IBMPlexSansArabic-Medium.otf",
      weight: "500",
      style: "medium",
    },
  ],
  variable: "--font-ibm-arabic",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body
        className={`${ibmArabic.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
